---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maturity-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maturity-board
  template:
    metadata:
      labels:
        app: maturity-board
    spec:
      containers:
      - name: maturity-board
        image: khinkali/maturity-board:0.0.2
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 2
          timeoutSeconds: 1
          periodSeconds: 2
        livenessProbe:
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 2
          timeoutSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html/config
      volumes:
      - name: config
        configMap:
          name: maturity-config
          items:
          - key: config.json
            path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: maturity-board
spec:
  selector:
    app: maturity-board
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30221
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maturity-config
data:
  config.json: |-
    {
      "baseUrl":"http://5.189.154.24:30222"
    }